stages:
  - mirror

variables:
  # Disables GitLab’s default git clone, we'll do it manually:
  GIT_STRATEGY: none

mirror_from_github:
  image: alpine:latest
  stage: mirror
  before_script:
    - apk add --no-cache git openssh-client

  script:
    # 1. Clone your GitHub repo as a bare mirror
    - git clone --mirror https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$GITHUB_USER/flux.git github-repo.git

    # 2. Change into that mirror repo
    - cd github-repo.git

    # 3. Point the 'origin' push URL to GitLab
    - git remote set-url --push origin https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/$CI_PROJECT_PATH.git

    # 4. Push all branches and tags back into GitLab
    - git push --mirror origin

  only:
    - schedules
